spring:
  application:
    name: service-feign

server:
  port: 8060

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka

feign:
  hystrix:
    enabled: true


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
