server:
  port: 8020

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka

spring:
  application:
    name: gateway
  cloud:
    gateway:
#      discovery:
#        locator:
#          enabled: true
      routes:
        - id: service-feign
          uri: lb://service-feign
          predicates:
            - Path=/service-feign/**
          filters:
            - RewritePath=/service-feign/(?<segment>.*), /$\{segment}
        - id: open-api
          uri: lb://open-api
          predicates:
              - Path=/open-api/**
          filters:
              - RewritePath=/open-api/(?<segment>.*), /$\{segment}
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    org.springframework.cloud.gateway: debug